name = "uptimeflare"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "uptimeflare-db"
database_id = "969bb8bb-4c96-4071-ba81-e7d2fcf795f2"
